"""
Deliverable writer -- turns the metrics / success-criteria / manifest dicts
produced by ``src/pipeline.py`` into the human-readable ``results/report.md``.

Pure formatting: no computation, no side effects beyond writing the file.
"""
from __future__ import annotations


# ---------------------------------------------------------------------------
def write_report(outdir, cfg, metrics, sc, manifest, band, df, amb, yte):
    ft = metrics["full_test"]
    bt = metrics["ambiguous_band_test"]
    q = manifest["quantum_resource"]

    def row(nm, d):
        cm = d["confusion_matrix"]
        return (f"| {nm} | {d['auroc']:.4f} | {d['auprc']:.4f} | {d['f1']:.4f} | "
                f"{d['precision']:.4f} | {d['recall']:.4f} | "
                f"{cm['tp']}/{cm['fp']}/{cm['fn']}/{cm['tn']} |")

    c1 = metrics["deltas"]["c1_auprc_Q3_vs_B4_full"]
    rc0 = cfg["routing"]["target_fraud_recall"]
    c2 = metrics["deltas"][f"c2_fdr_Q3_vs_B4_recall{rc0}"]
    c3 = metrics["deltas"]["c3_auprc_Q2_vs_ESN_band"]
    st = metrics["operational"]["distilled_student"]

    md = f"""# Abstraction - PoC results

*Hybrid LightGBM + Quantum Reservoir Computing for card-not-present fraud detection.*
Auto-generated by `run_experiment.py`. Runtime {manifest['runtime_seconds']:.0f}s.

## 1. Data

{"**IEEE-CIS Fraud Detection (real Kaggle data)** - the HSBC brief's primary dataset. `train_transaction.csv` left-joined with `train_identity.csv`; the unlabelled `test_*.csv` is the Kaggle leaderboard split so evaluation uses a chronological split of the training file (same protocol as the synthetic run)." if cfg["run"].get("data_source") == "ieee" else "Synthetic CNP transactions (IEEE-CIS stand-in; Kaggle credentials unavailable in this environment). Generator reproduces the properties HSBC calls out."}

- transactions: **{len(df):,}**, fraud rate **{df.isFraud.mean():.2%}**, entities {df.entity.nunique():,}
- fraud composition: {df[df.isFraud==1].fraud_type.value_counts().to_dict()}
- split: chronological 60/20/20 (FROZEN)

## 2. Architecture

```
transaction + history
  -> preprocessing (leakage-safe: every feature uses only rows with time < t)
  -> LightGBM (static + standard past-only aggregate features) [B4, production baseline]
     (B5 = B4 + aggressive hand-built temporal features, reported for honesty)
  -> isotonic calibration (fit on validation only)  -> p0
  -> ambiguity router:  p0 < tau_low  -> approve
                        p0 > tau_high -> decline / review
                        tau_low <= p0 <= tau_high -> QRC second opinion
  -> sequence builder (K={cfg['sequence']['K']} past txns of the same entity_key)
  -> fixed quantum reservoir (transverse-field Ising, {q['n_qubits']} qubits, NOT trained)
  -> measurement features z_qrc  ({q['observables_per_node']} observables x {cfg['qrc']['virtual_nodes']} virtual nodes + trajectory summary; dim {q['embedding_dim']})
  -> logistic fusion  [logit(p0), z_qrc, context]  -> p_final
  -> decision + grouped feature attribution
  -> (offline) distillation to a classical student for the 100-300 ms path
```

Frozen thresholds: band = [{band['tau_low']:.4f}, {band['tau_high']:.4f}],
t* = {band['t_star']:.4f}, hybrid decision threshold = {manifest['frozen']['hybrid_decision_threshold']:.4f}
(all chosen on validation, target fraud recall {rc0}).
Routing rate on test: **{metrics['operational']['routing_rate_test']:.1%}**,
fraud rate inside the band **{metrics['operational']['fraud_rate_in_band_test']:.1%}**
(vs {yte.mean():.1%} overall) - the router does concentrate the hard cases.

## 3. Quantum approach (challenge output: encoding + circuit design)

- **Encoding**: each step feature f in [0,1] -> single-qubit state
  `sqrt(1-f)|0> + sqrt(f)|1>` (RY(2 asin sqrt f)). {cfg['qrc']['input_qubits']} input
  qubits x {cfg['qrc']['reupload_rounds']} data-re-uploading rounds = up to 9 features/step.
- **Reservoir**: fully-connected transverse-field Ising,
  `H = sum J_ij X_i X_j + h sum Z_i`, `J_ij ~ U(-J/2, J/2)` drawn once per
  `reservoir_seed` and frozen. Evolution `exp(-i H dt)`, `dt={cfg['qrc']['dt']}`.
- **Injection** is a CPTP map (partial trace of input qubits + fresh product
  state) - this contraction is what gives the reservoir fading memory.
- **Read-out**: `<Z_i>` and `<Z_i Z_j>` at {cfg['qrc']['virtual_nodes']} virtual
  nodes (time multiplexing) of the final step, plus per-step trajectory
  mean/delta. Only a regularised logistic readout is trained.
- **Resource**: {q['n_qubits']} qubits, {q['evolution_steps_per_txn']} evolution
  sub-steps per transaction, embedding dim {q['embedding_dim']}, shots
  {q['shots']}. Simulator: exact NumPy density matrix; PennyLane/Braket-portable
  circuit cross-checked in `src/qrc_pennylane.py`.

## 4. Results - full held-out test set

| model | AUC-ROC | AUPRC | F1 | precision | recall | TP/FP/FN/TN |
|---|---|---|---|---|---|---|
{row('B0 logreg (static)', ft['B0_logreg_static'])}
{row('B1 LightGBM (static)', ft['B1_lgbm_static'])}
{row('B4 LightGBM (standard aggregates)', ft['B4_lgbm_aggregates'])}
{row('B4 calibrated', ft['B4_calibrated'])}
{row('B5 LightGBM (aggressive manual temporal FE)', ft['B5_lgbm_manual_temporal_FE'])}
{row('B_catboost (same features as B4)', ft['B_catboost_aggregates'])}
{row('ESN hybrid (end-to-end)', ft['ESN_end2end'])}
{row('Q3 QRC hybrid (end-to-end)', ft['Q3_hybrid_end2end'])}

(confusion matrix at each model's operating threshold; B4/ESN at t*, Q3 at the
frozen hybrid threshold.)

**Where the value sits.** B5 (aggressive hand-built temporal features on the
same GBDT) vs B4: dAUPRC {metrics['deltas']['auprc_B5_vs_B4_full']['delta']:+.4f}
CI [{metrics['deltas']['auprc_B5_vs_B4_full']['ci_low']:+.4f}, {metrics['deltas']['auprc_B5_vs_B4_full']['ci_high']:+.4f}].
Q3 hybrid vs B5: dAUPRC {metrics['deltas']['auprc_Q3_vs_B5_manualFE_full']['delta']:+.4f}
CI [{metrics['deltas']['auprc_Q3_vs_B5_manualFE_full']['ci_low']:+.4f}, {metrics['deltas']['auprc_Q3_vs_B5_manualFE_full']['ci_high']:+.4f}].
Read: how much of the ordered-sequence signal a analyst can capture by hand (B5-B4),
and whether the reservoir adds anything on top of that (Q3-B5).

**Does B4's strength depend on picking LightGBM?** CatBoost (same feature set
as B4, no other change) vs B4: dAUPRC
{metrics['deltas']['auprc_CatBoost_vs_B4_full']['delta']:+.4f}
CI [{metrics['deltas']['auprc_CatBoost_vs_B4_full']['ci_low']:+.4f}, {metrics['deltas']['auprc_CatBoost_vs_B4_full']['ci_high']:+.4f}].
Per the IEEE-CIS 1st-place writeup, CatBoost was in fact the strongest single
GBDT of the three they ensembled (private-LB AUC: CatBoost 0.9408, LightGBM
0.9384, XGBoost 0.9324) - this row checks whether that pattern shows up here too.

{_smoothing_section(metrics)}

## 5. Results - ambiguous band only (where QRC actually operates)

| model | AUC-ROC | AUPRC | F1 | precision | recall | TP/FP/FN/TN |
|---|---|---|---|---|---|---|
{row('B4 p0 (routed rows)', bt['B4_p0'])}
{row('Q0 QRC-only', bt['Q0_qrc_only'])}
{row('Q1 score fusion', bt['Q1_score_fusion'])}
{row('Q2 feature fusion', bt['Q2_feature_fusion'])}
{row('Q2 no-p0 (ablation)', bt['Q2_no_p0_ablation'])}
{_bandrow(bt, 'Q_deployed')}
{_bandrow(bt, 'ESN_deployed')}

## 6. Pre-registered success criteria

| # | criterion | result | verdict |
|---|---|---|---|
| C1 | dAUPRC(Q3 vs B4, full test) > 0, 95% CI > 0 | {c1['delta']:+.4f}  CI [{c1['ci_low']:+.4f}, {c1['ci_high']:+.4f}] | {'PASS' if sc['c1_delta_auprc_positive_ci']['pass_'] else 'fail'} |
| C2 | false-decline rate reduced at recall {rc0}, 95% CI < 0 | {c2['delta']:+.4f}  CI [{c2['ci_low']:+.4f}, {c2['ci_high']:+.4f}] | {'PASS' if sc['c2_false_decline_reduced_ci']['pass_'] else 'fail'} |
| C3 | Q2 at least at parity with the classical ESN on the band (95% CI low > -0.02; "beats" = CI low > 0) | {c3['delta']:+.4f}  CI [{c3['ci_low']:+.4f}, {c3['ci_high']:+.4f}]  (beats={sc['c3_vs_esn_on_band']['beats_esn']}) | {'PASS' if sc['c3_vs_esn_on_band']['pass_'] else 'fail'} |
| C4 | holds across reservoir seeds {manifest['frozen']['reservoir_seeds']} | see metrics.json > seeds | {'PASS' if sc['c4_holds_across_seeds']['pass_'] else 'fail'} |

**Overall measurable improvement: {'YES' if sc['overall_measurable_improvement'] else 'NO'}**

> {sc['note']}

## 7. Ablations (band AUPRC)

The deployment guard (section 5/6 - never deploy worse than `p0`) is **disabled**
for every row below: an ablation must show the true damage of a destructive
intervention (shuffled order, no entanglement, few shots, ...), not have it
masked by a silent fallback to `p0`. So these numbers are not directly the
Q2/Q3 numbers reported above; read them relative to the "ideal (unguarded)" row.

{_ablation_table(metrics)}

## 8. Distillation for production

| | band AUPRC | full-test AUPRC | latency |
|---|---|---|---|
| Q3 hybrid (needs offline QRC) | {st['hybrid_band_auprc']:.4f} | - | not real-time |
| distilled classical student | {st['band_auprc']:.4f} | {st['full_test_auprc']:.4f} | {st['inference_latency_ms_per_txn']:.4f} ms/txn |

The student runs comfortably inside the 100-300 ms authorisation budget; it
recovers {100*st['band_auprc']/max(st['hybrid_band_auprc'],1e-9):.0f}% of the
hybrid's band AUPRC.

## 9. Feature attribution (challenge output #3)

- LightGBM path: SHAP / tree contributions, per transaction (see `predictions.csv`).
- Fusion path: grouped contribution {metrics['fusion_group_attribution']}
  (no single quantum observable is claimed to "cause" fraud).

## 10. Honest limitations

- {"Real IEEE-CIS data (chronological holdout). `entity_key` is a proxy (no true customer ID in IEEE-CIS), so per-entity history is noisier than a real customer ID would give." if cfg["run"].get("data_source") == "ieee" else "Synthetic data: absolute numbers are not IEEE-CIS numbers; the *comparison* (QRC vs ESN vs LightGBM under identical splits) is the transferable result."}
- A {q['n_qubits']}-qubit reservoir is, per Fujii & Nakajima, in the class of a
  ~100-500 node ESN. Do not extrapolate to "quantum advantage".
- Quantum execution is offline. Production value = feature discovery + distillation.
- `entity_key` is a proxy; `metrics.json` / config carry the E1 vs E2 sensitivity hook.
"""
    open(outdir / "report.md", "w").write(md)


def _smoothing_section(metrics):
    s = metrics.get("smoothing", {})
    if not s.get("enabled"):
        return "_entity-level smoothing disabled for this run._"
    dc, db = s["delta_causal"], s["delta_batch_AUDIT_ONLY"]
    return f"""**Entity-level smoothing** (the IEEE-CIS 1st-place solution's other big lever
besides feature engineering: replace a transaction's score with its card/client's
average score). Alpha frozen on validation = **{s['alpha_star']}** (1.0 = no
smoothing, 0.0 = fully replaced by the entity mean) from grid {s['alpha_grid']}.

| variant | deployable in HSBC's real-time path? | AUPRC | delta vs B4 | 95% CI |
|---|---|---|---|---|
| B4 baseline | - | {s['auprc_baseline_B4']:.4f} | - | - |
| + causal smoothing (past-only entity mean) | **yes** | {s['auprc_causal_smooth']:.4f} | {dc['delta']:+.4f} | [{dc['ci_low']:+.4f}, {dc['ci_high']:+.4f}] |
| + batch smoothing (whole-batch entity mean, exact Kaggle trick) | **no - uses each entity's future test transactions** | {s['auprc_batch_smooth_AUDIT_ONLY']:.4f} | {db['delta']:+.4f} | [{db['ci_low']:+.4f}, {db['ci_high']:+.4f}] |

The batch row is reported only as an offline/audit ceiling - it is exactly what
the Kaggle-winning team did on their one-shot test submission, but HSBC's
<300ms authorization flow does not have an entity's future transactions
available yet, so it can never be deployed as-is."""


def _bandrow(bt, prefix):
    key = next((k for k in bt if k.startswith(prefix)), None)
    if key is None:
        return f"| {prefix} | - | - | - | - | - | - |"
    d = bt[key]
    cm = d["confusion_matrix"]
    return (f"| {key} | {d['auroc']:.4f} | {d['auprc']:.4f} | {d['f1']:.4f} | "
            f"{d['precision']:.4f} | {d['recall']:.4f} | "
            f"{cm['tp']}/{cm['fp']}/{cm['fn']}/{cm['tn']} |")


def _ablation_table(metrics):
    ab = metrics.get("ablations", {})
    if not ab:
        return "_ablations disabled_"
    lines = ["| ablation | band AUPRC | vs ideal |", "|---|---|---|"]
    ideal = ab.get("ideal_feature_fusion_band_auprc", float("nan"))
    lines.append(f"| ideal feature fusion (unguarded) | {ideal:.4f} | - |")
    dep = ab.get("ideal_feature_fusion_band_auprc_guarded_deployed")
    if dep is not None:
        lines.append(f"| _(for reference: guarded/deployed number, section 5)_ | {dep:.4f} | {dep-ideal:+.4f} |")
    for k in ("no_entanglement", "random_reservoir", "shuffle_sequence",
              "no_history_K1"):
        if k in ab:
            lines.append(f"| {k} | {ab[k]:.4f} | {ab[k]-ideal:+.4f} |")
    for k, dd in (("qubit_sweep_band_auprc", "qubits"),
                  ("K_sweep_band_auprc", "K"),
                  ("dt_sweep_band_auprc", "dt")):
        if k in ab:
            for kk, vv in ab[k].items():
                lines.append(f"| {dd}={kk} | {vv:.4f} | {vv-ideal:+.4f} |")
    if "shots_sweep" in ab:
        for sh, au in ab["shots_sweep"]:
            lines.append(f"| shots={sh} | {au:.4f} | {au-ideal:+.4f} |")
    return "\n".join(lines)

